version: "3.9"

services:
  api:
    image: ghcr.io/nephrolog-lt/nephrolog-api:latest
    env_file:
      - secrets/.env
    labels:
      - lt.nephrolog.api
    deploy:
      replicas: 2
      update_config:
        delay: 5s
        order: stop-first
    volumes:
      - static_volume:/srv/nephrolog-api/static
      - media_volume:/srv/nephrolog-api/media
      - /srv/nephrolog-api/secrets:/srv/nephrolog-api/secrets
    networks:
      - nginx_network
      - database_network
      - redis_network

  postgres:
    image: postgres:13.1
    env_file:
      - secrets/.env
    networks:
      - database_network
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
    labels:
      - lt.nephrolog.postgres
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: redis:6.0
    networks:
      - redis_network
    labels:
      - lt.nephrolog.redis
    volumes:
      - redis_volume:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]

  nginx:
    image: nginx:1.19
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/nephrolog-api/nginx/conf.d:/etc/nginx/conf.d
      - /srv/nephrolog-api/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/srv/nephrolog-api/static
      - media_volume:/srv/nephrolog-api/media
    networks:
      - nginx_network
    labels:
      - lt.nephrolog.nginx

networks:
  nginx_network:
    driver: overlay
  database_network:
    driver: overlay
  redis_network:
    driver: overlay

volumes:
  postgres_volume:
  static_volume:
  media_volume:
  redis_volume: